// <auto-generated />
using System;
using EsercizioVivaio;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EsercizioVivaio.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cognome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clienti");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Dettaglio_Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrdineID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PiantaID")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantita")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OrdineID");

                    b.HasIndex("PiantaID");

                    b.ToTable("Dettaglio_Ordine");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Fiore", b =>
                {
                    b.Property<int>("PiantaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Colore")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PiantaID");

                    b.ToTable("Fiore");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Frutta", b =>
                {
                    b.Property<int>("PiantaID")
                        .HasColumnType("INTEGER");

                    b.Property<float>("Produttivita")
                        .HasColumnType("REAL");

                    b.HasKey("PiantaID");

                    b.ToTable("Frutta");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Giardino", b =>
                {
                    b.Property<int>("PiantaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Stagione")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PiantaID");

                    b.ToTable("Giardino");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Ordine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Data")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mod_pagamento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Ordini");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Pianta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("Prezzo")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Piante");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Dettaglio_Ordine", b =>
                {
                    b.HasOne("EsercizioVivaio.Classi_Modello.Ordine", "Ordine")
                        .WithMany("Dettaglio_Ordini")
                        .HasForeignKey("OrdineID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EsercizioVivaio.Classi_Modello.Pianta", "Pianta")
                        .WithMany("Dettaglio_Ordini")
                        .HasForeignKey("PiantaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Fiore", b =>
                {
                    b.HasOne("EsercizioVivaio.Classi_Modello.Pianta", "Pianta")
                        .WithOne("Fiore")
                        .HasForeignKey("EsercizioVivaio.Classi_Modello.Fiore", "PiantaID");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Frutta", b =>
                {
                    b.HasOne("EsercizioVivaio.Classi_Modello.Pianta", "Pianta")
                        .WithOne("Frutta")
                        .HasForeignKey("EsercizioVivaio.Classi_Modello.Frutta", "PiantaID");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Giardino", b =>
                {
                    b.HasOne("EsercizioVivaio.Classi_Modello.Pianta", "Pianta")
                        .WithOne("Giardino")
                        .HasForeignKey("EsercizioVivaio.Classi_Modello.Giardino", "PiantaID");
                });

            modelBuilder.Entity("EsercizioVivaio.Classi_Modello.Ordine", b =>
                {
                    b.HasOne("EsercizioVivaio.Classi_Modello.Cliente", "Cliente")
                        .WithMany("Ordini")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
